# Generated by Django 5.2.5 on 2025-08-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='station',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
